version: '3'

includes:
  root:
    taskfile: ../Taskfile.yaml
    flatten: true
    vars:
      PACKAGE_MANAGER: uv

vars:
  PWD:
    sh: pwd
  DAGSTER_HOME: "{{.PWD}}/dagster"
  DAGSTER_DEFAULT_FILE: src/dagster_catboost.py
  GITHUB_TOKEN:
    sh: gh auth token

dotenv: ['.env']

tasks:
  dagster:run:
    desc: Run Dagster job
    cmds:
      - |
        if [ "{{.CLI_ARGS}}" != "" ]; then
          DAGSTER_HOME="{{.DAGSTER_HOME}}" uv run dagster job execute {{.CLI_ARGS}}
        else
          DAGSTER_HOME="{{.DAGSTER_HOME}}" uv run dagster job execute -f {{.DAGSTER_DEFAULT_FILE}} -j __ASSET_JOB
        fi

  dagster:dev:
    desc: Run Dagster dev server
    cmds:
      - |
        if [ "{{.CLI_ARGS}}" != "" ]; then
          DAGSTER_HOME="{{.DAGSTER_HOME}}" uv run dagster dev {{.CLI_ARGS}}
        else
          DAGSTER_HOME="{{.DAGSTER_HOME}}" uv run dagster dev -f {{.DAGSTER_DEFAULT_FILE}}
        fi

  dagster:get-prod-state:
    desc: Downloads latest dagster-prod-state from github artifacts to directory dagster
    cmds:
      - rm -rf dagster/artifacts/*
      - rm -rf dagster/compute_logs/*
      - rm -rf dagster/logs/*
      - rm -rf dagster/sqlite/*
      - gh run download --name dagster-prod-state --dir dagster

  dagster:run-prod-workflow:
    desc: runs the prod github actions workflow locally, to be able to use and update the prod artifact
    dir: ..
    cmds:
      - |
        act workflow_dispatch -W .github/workflows/prod__run-dagster.yaml \
          --container-architecture linux/amd64 \
          --secret GITHUB_TOKEN={{.GITHUB_TOKEN}} \
          --secret MOTHERDUCK_TOKEN={{.MOTHERDUCK_TOKEN}} \
          --var APP_ENV={{.APP_ENV}} \
          -P ubuntu-latest=catthehacker/ubuntu:full-latest
